name: twin_project
description: A Flutter project for TWIN.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  flutter_dotenv: ^5.2.1
  sqflite: ^2.4.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.0  

dependency_overrides:
  path_provider_android: 2.2.22

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/TWIN_ico.png
    - assets/images/Главный2.png
    - assets/images/Вход.png
    - assets/images/Регистрация.png
    - assets/images/Профиль.png
    - assets/images/Осебе.png
    - assets/images/Настройки.png
    - assets/images/Анкеты.png
  fonts:
    - family: Rosarivo
      fonts:
        - asset: assets/fonts/Rosarivo-Regular.ttf
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest-Regular.ttf
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/TWIN_ico.png"
  # Для Android 8.0+ (адаптивные иконки)
  adaptive_icon_background: "#FFE8C8"  # Цвет фона (ваш оранжевый)
  adaptive_icon_foreground: "assets/images/TWIN_ico.png"
  # Удалить старые иконки
  remove_alpha_ios: true
